name: Fetch product images (SerpAPI)
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: npm run images:serp
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update product image URLs via SerpAPI"
          branch: serpapi/image-updates
          title: "Update product images via SerpAPI"
          body: "Adds/updates external image URLs in data/*.json"
          add-paths: |
            data/*.json
