name: Fetch product images (SerpAPI)
on:
  workflow_dispatch: {}
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: npm run images:serp
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update product image URLs via SerpAPI" || echo "No changes"
          git push
